import 'package:flutter_application_1/base/res/media.dart';

List<Map<String, dynamic>> restaurantList = [
  {
    "id": 1,
    "image": AppMedia.breakfastInBed,
    "status": "Open",
    "rating": "4.5",
    "name": "Happy Bones",
    "address": "123 London St, London, UK",
    "category": "Outdoor",
    "distance": "12 KM",
    "bookmark": false,
  },
  {
    "id": 2,
    "image": AppMedia.dinnerIsServed,
    "status": "Open",
    "rating": "4.7",
    "name": "The Cozy Corner",
    "address": "456 Baker St, London, UK",
    "category": "Indoor",
    "distance": "8 KM",
    "bookmark": false,
  },
  {
    "id": 3,
    "image": AppMedia.breakfastInBed,
    "status": "Closed",
    "rating": "4.2",
    "name": "Sunny Side Up",
    "address": "789 High St, London, UK",
    "category": "Brunch",
    "distance": "5 KM",
    "bookmark": true,
  },
  {
    "id": 4,
    "image": AppMedia.breakfastInBed,
    "status": "Open",
    "rating": "4.8",
    "name": "Gourmet Garden",
    "address": "321 Park Ave, London, UK",
    "category": "Fine Dining",
    "distance": "10 KM",
    "bookmark": false,
  },
  {
    "id": 5,
    "image": AppMedia.breakfastInBed,
    "status": "Open",
    "rating": "4.6",
    "name": "Pasta Paradise",
    "address": "654 Elm St, London, UK",
    "category": "Italian",
    "distance": "15 KM",
    "bookmark": true,
  },
  {
    "id": 6,
    "image": AppMedia.breakfastInBed,
    "status": "Open",
    "rating": "4.3",
    "name": "Sushi Spot",
    "address": "987 River Rd, London, UK",
    "category": "Japanese",
    "distance": "7 KM",
    "bookmark": false,
  },
  // You can add more unique restaurant entries here
];
